#!/system/bin/sh
cmd='sh /system/etc/init.plain.kerneltweak.sh'
sha=0
sdcustomdensity=$(cat $EXTERNAL_STORAGE/customdensity | sed 's/customdensity*.//')
if [ -n $sdcustomdensity ]; then
setprop persist.sys.customdensity $sdcustomdensity
else
echo "customdensity="$(getprop ro.sf.lcd_density) > $EXTERNAL_STORAGE/customdensity
fi
if [ -z $(getprop persist.sys.updateinterval) ]
then
setprop persist.sys.updateinterval 10
fi
while [ -z $(getprop persist.sys.enable_plaintweak) ]
do
  if [ ! -f /data/property/persist.sys.enable_plaintweak ]; then
    setprop persist.sys.enable_plaintweak 1
  fi
  sleep $(getprop persist.sys.updateinterval)
done # waiting for boot complete
while [ -z $(getprop persist.sys.stocktcpcong) ]
do
setprop persist.sys.stocktcpcong $(cat /proc/sys/net/ipv4/tcp_congestion_control)
done
while [ -z $(getprop persist.sys.stockscheduler) ]
do
setprop persist.sys.stockscheduler $(cat /sys/block/mmcblk0/queue/scheduler | sed 's/.*[[]//g' | sed 's/[]].*//g')
done
while [ -z $(getprop persist.sys.stockgov) ]
do
setprop persist.sys.stockgov $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
done
while [ -z $(getprop persist.sys.stockminkhz) ]
do
setprop persist.sys.stockminkhz $(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq)
done
while [ -z $(getprop persist.sys.stockmaxkhz) ]
do
setprop persist.sys.stockmaxkhz $(cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq)
done
$cmd
echo "Plain-tweak watcher is online"
#Using original watch scripting from https://gist.github.com/mikesmullin/6401258
path=$EXTERNAL_STORAGE/plaintweak
update_sha() {
  sha=`sha1sum $path`
}
update_sha
previous_sha=$sha
build() {
  echo "Change detected; Invoking /system/etc/init.plain.kerneltweak.sh"
  $cmd
}
coreset2(){
if [ -d /sys/devices/system/cpu/cpu1/cpufreq ]
then
	echo $(getprop persist.sys.maxkhz) > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
	echo $(getprop persist.sys.minkhz) > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
	echo $(getprop persist.sys.gov) > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
fi

if [ -d /sys/devices/system/cpu/cpu2/cpufreq ]
then
	if [ -z $(getprop persist.sys.maxkhz2) ]
	then
		echo $(getprop persist.sys.maxkhz) > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
	else
		echo $(getprop persist.sys.maxkhz2) > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
	fi
	if [ -z $(getprop persist.sys.minkhz2) ]
	then
		echo $(getprop persist.sys.minkhz) > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
	else
		echo $(getprop persist.sys.minkhz2) > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
	fi
	if [ -z $(getprop persist.sys.gov2) ]
	then
		echo $(getprop persist.sys.gov) > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
	else
		echo $(getprop persist.sys.gov2) > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
	fi
fi

if [ -d /sys/devices/system/cpu/cpu3/cpufreq ]
then
	if [ -z $(getprop persist.sys.maxkhz2) ]
	then
		echo $(getprop persist.sys.maxkhz) > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq
	else
		echo $(getprop persist.sys.maxkhz2) > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq
	fi

	if [ -z $(getprop persist.sys.minkhz2) ]
	then
		echo $(getprop persist.sys.minkhz) > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
	else
		echo $(getprop persist.sys.minkhz2) > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
	fi
	if [ -z $(getprop persist.sys.gov2) ]
	then
		echo $(getprop persist.sys.gov) > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
	else
		echo $(getprop persist.sys.gov2) > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
	fi
fi
}
compare() {
  update_sha
  if [[ $sha != $previous_sha ]] ; then
    build
    previous_sha=$sha
  fi
  coreset2
}
trap build SIGINT
trap exit SIGQUIT
while true; do
sysrw
if [ $(getprop persist.sys.enable_plaintweak) == "1" ]; then
  compare
  else
  build
fi
  sleep $(getprop persist.sys.updateinterval)
sysro
done
